import Head from "next/head";
import { useMoralis } from "react-moralis";
import Register from "../components/Register";
import Account from "./account";

export default function Home() {
  const supportedChains = ["80001"];
  const { isWeb3Enabled, chainId } = useMoralis();
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full">
        <Account />
        {isWeb3Enabled ? (
          <div>
            {supportedChains.includes(parseInt(chainId).toString()) ? (
              <div className="flex flex-row">
                <Register />
              </div>
            ) : (
              <div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
            )}
          </div>
        ) : (
          <div>Please connect to a Wallet</div>
        )}
      </main>
    </div>
  );
}
